//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegisterPanelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegisterPanelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMS.Desktop.Localization.RegisterPanelStrings", typeof(RegisterPanelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parece ser que la hora de tu equipo no está correcta. Checa que la zona horaria de tu equipo, la fecha y la hora estén correctos e intenta de nuevo..
        /// </summary>
        internal static string Error_RequestSignature {
            get {
                return ResourceManager.GetString("Error_RequestSignature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Ouch! Parece que nuestros servidores se están quemando. Intenta de nuevo en un ratito..
        /// </summary>
        internal static string Error_ServerError {
            get {
                return ResourceManager.GetString("Error_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éste e-mail ya está registrado en otra cuenta de KMS. Intenta con otra..
        /// </summary>
        internal static string Validation_EmailAlreadyInUse {
            get {
                return ResourceManager.GetString("Validation_EmailAlreadyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las direcciones de correo no coinciden ¡revísalas bien!.
        /// </summary>
        internal static string Validation_EmailMismatch {
            get {
                return ResourceManager.GetString("Validation_EmailMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Esto está muy corto o está vacío! No puede estar vacío..
        /// </summary>
        internal static string Validation_GenericTooShort {
            get {
                return ResourceManager.GetString("Validation_GenericTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ésta fecha es inválida (no existe). ¡Bonita broma!.
        /// </summary>
        internal static string Validation_InvalidBirthDate {
            get {
                return ResourceManager.GetString("Validation_InvalidBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Éste e-mail no tiene un formato correcto..
        /// </summary>
        internal static string Validation_InvalidEmail {
            get {
                return ResourceManager.GetString("Validation_InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes elegir tu País y Estado..
        /// </summary>
        internal static string Validation_MustChooseCountryAndSubdivision {
            get {
                return ResourceManager.GetString("Validation_MustChooseCountryAndSubdivision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes elegir si eres hombre o mujer..
        /// </summary>
        internal static string Validation_MustChooseGender {
            get {
                return ResourceManager.GetString("Validation_MustChooseGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debes elegir tu peso y estatura. ¡Que no te de pena!.
        /// </summary>
        internal static string Validation_MustChooseHeightAndWeight {
            get {
                return ResourceManager.GetString("Validation_MustChooseHeightAndWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña que escribiste arriba no coincide con la que escribiste aquí. Chécalo de nuevo..
        /// </summary>
        internal static string Validation_PasswordMismatch {
            get {
                return ResourceManager.GetString("Validation_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La contraseña que elegiste es demasidado corta. Tiene que tener al menos 6 carácteres (números, letras o símbolos)..
        /// </summary>
        internal static string Validation_PasswordTooShort {
            get {
                return ResourceManager.GetString("Validation_PasswordTooShort", resourceCulture);
            }
        }
    }
}
