//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KMS.Desktop.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LoadingPanelStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoadingPanelStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KMS.Desktop.Localization.LoadingPanelStrings", typeof(LoadingPanelStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos iniciando tu sesión en KMS.
        /// </summary>
        internal static string CheckingCredentials {
            get {
                return ResourceManager.GetString("CheckingCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conecta tu pulsera.
        /// </summary>
        internal static string ConnectDevice {
            get {
                return ResourceManager.GetString("ConnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos conectando con KMS.
        /// </summary>
        internal static string ConnectingToCloud {
            get {
                return ResourceManager.GetString("ConnectingToCloud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estamos creando tu nueva y poderosa cuenta de KMS....
        /// </summary>
        internal static string CreatingAccount {
            get {
                return ResourceManager.GetString("CreatingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No desconectes tu pulsera.
        /// </summary>
        internal static string DoNotDisconnectDevice {
            get {
                return ResourceManager.GetString("DoNotDisconnectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seguimos trabajando ....
        /// </summary>
        internal static string GenericKeepWaiting {
            get {
                return ResourceManager.GetString("GenericKeepWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera un momento ....
        /// </summary>
        internal static string GenericWait {
            get {
                return ResourceManager.GetString("GenericWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podría ser que no tengas acceso a Internet, o tu conexión esté muy lenta..
        /// </summary>
        internal static string MaybeNoInternet {
            get {
                return ResourceManager.GetString("MaybeNoInternet", resourceCulture);
            }
        }
    }
}
